INFO 2024-06-03 22:43:40,958 autoreload 19356 6268 Watching for file changes with StatReloader
INFO 2024-06-03 22:44:00,780 basehttp 19356 3540 "GET /about/ HTTP/1.1" 200 851
INFO 2024-06-03 22:44:03,121 basehttp 19356 3540 "GET /about/ HTTP/1.1" 200 851
INFO 2024-06-03 22:44:10,034 basehttp 19356 3540 "GET / HTTP/1.1" 200 1604
WARNING 2024-06-03 22:44:18,447 log 19356 3540 Not Found: /random_roll
WARNING 2024-06-03 22:44:18,448 basehttp 19356 3540 "GET /random_roll HTTP/1.1" 404 2439
INFO 2024-06-03 22:44:29,663 basehttp 19356 3540 "GET /about/ HTTP/1.1" 200 851
INFO 2024-06-11 21:14:12,786 autoreload 21064 2512 Watching for file changes with StatReloader
INFO 2024-06-11 21:14:17,786 basehttp 21064 19460 "GET / HTTP/1.1" 200 1604
INFO 2024-06-11 21:25:11,338 autoreload 14032 2724 Watching for file changes with StatReloader
INFO 2024-07-01 20:21:10,370 autoreload 5316 7312 Watching for file changes with StatReloader
INFO 2024-07-01 20:22:09,817 autoreload 20012 24796 Watching for file changes with StatReloader
INFO 2024-07-01 20:24:20,042 autoreload 20012 24796 D:\GB\Django\Djangofirstproject\homework\hw_2app\urls.py changed, reloading.
INFO 2024-07-01 20:24:20,465 autoreload 22000 6328 Watching for file changes with StatReloader
INFO 2024-07-01 20:58:35,021 autoreload 22000 6328 D:\GB\Django\Djangofirstproject\homework\hw_2app\urls.py changed, reloading.
INFO 2024-07-01 20:58:35,556 autoreload 8708 26484 Watching for file changes with StatReloader
INFO 2024-07-01 20:59:58,568 autoreload 8708 26484 D:\GB\Django\Djangofirstproject\homework\hw_2app\urls.py changed, reloading.
INFO 2024-07-01 20:59:58,996 autoreload 1608 23008 Watching for file changes with StatReloader
INFO 2024-07-01 21:00:24,875 autoreload 26616 5356 Watching for file changes with StatReloader
INFO 2024-07-01 21:00:27,031 basehttp 26616 2436 "GET / HTTP/1.1" 200 1604
WARNING 2024-07-01 21:00:27,167 log 26616 2436 Not Found: /favicon.ico
WARNING 2024-07-01 21:00:27,167 basehttp 26616 2436 "GET /favicon.ico HTTP/1.1" 404 2544
INFO 2024-07-01 21:00:49,866 autoreload 14768 22324 Watching for file changes with StatReloader
INFO 2024-07-01 21:00:51,596 basehttp 14768 19516 "GET / HTTP/1.1" 200 1604
WARNING 2024-07-01 21:00:51,652 log 14768 19516 Not Found: /favicon.ico
WARNING 2024-07-01 21:00:51,652 basehttp 14768 19516 "GET /favicon.ico HTTP/1.1" 404 2544
INFO 2024-07-01 21:01:13,972 basehttp 14768 19516 "GET / HTTP/1.1" 200 1604
WARNING 2024-07-01 21:01:21,462 log 14768 19516 Not Found: /shop
WARNING 2024-07-01 21:01:21,462 basehttp 14768 19516 "GET /shop HTTP/1.1" 404 2523
WARNING 2024-07-01 21:01:34,968 log 14768 19516 Not Found: /shop/orders
WARNING 2024-07-01 21:01:34,974 basehttp 14768 19516 "GET /shop/orders HTTP/1.1" 404 2626
WARNING 2024-07-01 21:01:46,334 log 14768 19516 Not Found: /shop/orders/2
WARNING 2024-07-01 21:01:46,334 basehttp 14768 19516 "GET /shop/orders/2 HTTP/1.1" 404 2632
WARNING 2024-07-01 21:03:46,123 log 14768 19516 Not Found: /shop/orders/2
WARNING 2024-07-01 21:03:46,125 basehttp 14768 19516 "GET /shop/orders/2 HTTP/1.1" 404 2632
WARNING 2024-07-01 21:03:49,188 log 14768 19516 Not Found: /shop/orders/2
WARNING 2024-07-01 21:03:49,188 basehttp 14768 19516 "GET /shop/orders/2 HTTP/1.1" 404 2632
WARNING 2024-07-01 21:03:52,617 log 14768 19516 Not Found: /shop/orders/2
WARNING 2024-07-01 21:03:52,617 basehttp 14768 19516 "GET /shop/orders/2 HTTP/1.1" 404 2632
INFO 2024-07-01 21:05:49,848 autoreload 10560 13676 Watching for file changes with StatReloader
INFO 2024-07-01 21:05:51,506 basehttp 10560 27624 "GET / HTTP/1.1" 200 1604
WARNING 2024-07-01 21:06:02,452 log 10560 27624 Not Found: /shop
WARNING 2024-07-01 21:06:02,458 basehttp 10560 27624 "GET /shop HTTP/1.1" 404 2523
WARNING 2024-07-01 21:07:53,615 log 10560 27624 Not Found: /shop
WARNING 2024-07-01 21:07:53,615 basehttp 10560 27624 "GET /shop HTTP/1.1" 404 2523
WARNING 2024-07-01 21:07:55,298 log 10560 27624 Not Found: /shop
WARNING 2024-07-01 21:07:55,298 basehttp 10560 27624 "GET /shop HTTP/1.1" 404 2523
WARNING 2024-07-01 21:07:56,177 log 10560 27624 Not Found: /shop
WARNING 2024-07-01 21:07:56,177 basehttp 10560 27624 "GET /shop HTTP/1.1" 404 2523
WARNING 2024-07-01 21:07:56,543 log 10560 27624 Not Found: /shop
WARNING 2024-07-01 21:07:56,543 basehttp 10560 27624 "GET /shop HTTP/1.1" 404 2523
WARNING 2024-07-01 21:07:56,762 log 10560 27624 Not Found: /shop
WARNING 2024-07-01 21:07:56,762 basehttp 10560 27624 "GET /shop HTTP/1.1" 404 2523
WARNING 2024-07-01 21:07:56,936 log 10560 27624 Not Found: /shop
WARNING 2024-07-01 21:07:56,936 basehttp 10560 27624 "GET /shop HTTP/1.1" 404 2523
WARNING 2024-07-01 21:08:08,907 log 10560 27624 Not Found: /shop/
WARNING 2024-07-01 21:08:08,916 basehttp 10560 27624 "GET /shop/ HTTP/1.1" 404 2608
WARNING 2024-07-01 21:12:12,331 log 10560 27624 Not Found: /post
WARNING 2024-07-01 21:12:12,331 basehttp 10560 27624 "GET /post HTTP/1.1" 404 2523
WARNING 2024-07-01 21:12:31,199 log 10560 27624 Not Found: /app3
WARNING 2024-07-01 21:12:31,199 basehttp 10560 27624 "GET /app3 HTTP/1.1" 404 2523
WARNING 2024-07-01 21:13:08,074 log 10560 27624 Not Found: /shop/orders
WARNING 2024-07-01 21:13:08,082 basehttp 10560 27624 "GET /shop/orders HTTP/1.1" 404 2626
WARNING 2024-07-01 21:13:19,876 log 10560 27624 Not Found: /shop/orders
WARNING 2024-07-01 21:13:19,879 basehttp 10560 27624 "GET /shop/orders HTTP/1.1" 404 2626
WARNING 2024-07-01 21:13:25,511 log 10560 27624 Not Found: /shop/orders/2
WARNING 2024-07-01 21:13:25,515 basehttp 10560 27624 "GET /shop/orders/2 HTTP/1.1" 404 2632
WARNING 2024-07-01 21:14:37,186 log 10560 27624 Not Found: /shop/ orders/2
WARNING 2024-07-01 21:14:37,186 basehttp 10560 27624 "GET /shop/%20orders/2 HTTP/1.1" 404 2637
INFO 2024-07-01 21:20:51,230 autoreload 19672 16700 Watching for file changes with StatReloader
INFO 2024-07-01 21:20:53,872 basehttp 19672 768 "GET / HTTP/1.1" 200 1604
INFO 2024-07-01 21:22:12,710 autoreload 19672 16700 D:\GB\Django\Djangofirstproject\homework\homework\urls.py changed, reloading.
INFO 2024-07-01 21:22:13,166 autoreload 21624 8272 Watching for file changes with StatReloader
WARNING 2024-07-01 21:22:15,905 log 21624 12096 Not Found: /
WARNING 2024-07-01 21:22:15,905 basehttp 21624 12096 "GET / HTTP/1.1" 404 2166
WARNING 2024-07-01 21:22:24,926 log 21624 12096 Not Found: /shop
WARNING 2024-07-01 21:22:24,926 basehttp 21624 12096 "GET /shop HTTP/1.1" 404 2196
WARNING 2024-07-01 21:22:35,011 log 21624 12096 Not Found: /shop/
WARNING 2024-07-01 21:22:35,019 basehttp 21624 12096 "GET /shop/ HTTP/1.1" 404 2281
WARNING 2024-07-01 21:22:47,854 log 21624 12096 Not Found: /shop/orders/2
WARNING 2024-07-01 21:22:47,856 basehttp 21624 12096 "GET /shop/orders/2 HTTP/1.1" 404 2305
INFO 2024-07-01 21:23:35,902 autoreload 21624 8272 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-01 21:23:36,358 autoreload 22020 24412 Watching for file changes with StatReloader
WARNING 2024-07-01 21:23:41,530 log 22020 940 Not Found: /
WARNING 2024-07-01 21:23:41,530 basehttp 22020 940 "GET / HTTP/1.1" 404 2166
WARNING 2024-07-01 21:23:53,955 log 22020 940 Not Found: /shop
WARNING 2024-07-01 21:23:53,955 basehttp 22020 940 "GET /shop HTTP/1.1" 404 2196
WARNING 2024-07-01 21:23:56,646 log 22020 940 Not Found: /shop
WARNING 2024-07-01 21:23:56,647 basehttp 22020 940 "GET /shop HTTP/1.1" 404 2196
WARNING 2024-07-01 21:24:05,803 log 22020 940 Not Found: /shop/orders
WARNING 2024-07-01 21:24:05,803 basehttp 22020 940 "GET /shop/orders HTTP/1.1" 404 2299
WARNING 2024-07-01 21:24:10,082 log 22020 940 Not Found: /shop/orders
WARNING 2024-07-01 21:24:10,083 basehttp 22020 940 "GET /shop/orders HTTP/1.1" 404 2299
WARNING 2024-07-01 21:24:11,848 log 22020 940 Not Found: /shop/orders
WARNING 2024-07-01 21:24:11,848 basehttp 22020 940 "GET /shop/orders HTTP/1.1" 404 2299
WARNING 2024-07-01 21:24:13,482 log 22020 940 Not Found: /shop/orders
WARNING 2024-07-01 21:24:13,488 basehttp 22020 940 "GET /shop/orders HTTP/1.1" 404 2299
INFO 2024-07-01 21:24:35,377 autoreload 22020 24412 D:\GB\Django\Djangofirstproject\homework\hw_2app\urls.py changed, reloading.
INFO 2024-07-01 21:24:35,835 autoreload 21848 27560 Watching for file changes with StatReloader
WARNING 2024-07-01 21:24:37,994 log 21848 25700 Not Found: /
WARNING 2024-07-01 21:24:37,994 basehttp 21848 25700 "GET / HTTP/1.1" 404 2166
WARNING 2024-07-01 21:24:46,144 log 21848 25700 Not Found: /shop
WARNING 2024-07-01 21:24:46,144 basehttp 21848 25700 "GET /shop HTTP/1.1" 404 2196
WARNING 2024-07-01 21:24:49,221 log 21848 25700 Not Found: /shop/
WARNING 2024-07-01 21:24:49,223 basehttp 21848 25700 "GET /shop/ HTTP/1.1" 404 2268
INFO 2024-07-01 21:24:55,560 basehttp 21848 25700 "GET /shop/orders HTTP/1.1" 301 0
INFO 2024-07-01 21:24:55,574 basehttp 21848 25892 "GET /shop/orders/ HTTP/1.1" 200 502
INFO 2024-07-01 21:31:16,023 autoreload 21848 27560 D:\GB\Django\Djangofirstproject\homework\hw_2app\urls.py changed, reloading.
INFO 2024-07-01 21:31:16,491 autoreload 13348 25988 Watching for file changes with StatReloader
WARNING 2024-07-01 21:31:35,840 log 13348 7208 Not Found: /
WARNING 2024-07-01 21:31:35,840 basehttp 13348 7208 "GET / HTTP/1.1" 404 2166
INFO 2024-07-01 21:31:47,925 basehttp 13348 7208 "GET /shop/orders/ HTTP/1.1" 200 431
INFO 2024-07-01 21:32:32,863 basehttp 13348 7208 "GET /shop/orders/ HTTP/1.1" 200 431
INFO 2024-07-01 21:32:33,983 basehttp 13348 7208 "GET /shop/ HTTP/1.1" 200 463
INFO 2024-07-01 21:35:58,687 autoreload 13348 25988 D:\GB\Django\Djangofirstproject\homework\hw_2app\urls.py changed, reloading.
INFO 2024-07-01 21:35:59,117 autoreload 3500 16004 Watching for file changes with StatReloader
INFO 2024-07-01 21:36:06,477 basehttp 3500 26260 "GET /shop/ HTTP/1.1" 200 463
WARNING 2024-07-01 21:36:12,187 log 3500 26260 Not Found: /shop/orders/
WARNING 2024-07-01 21:36:12,187 basehttp 3500 26260 "GET /shop/orders/ HTTP/1.1" 404 2475
ERROR 2024-07-01 21:36:15,051 log 3500 26260 Internal Server Error: /shop/orders/2
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 23, in get_orders
    return render(request, 'hw_2app/orders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\defaulttags.py", line 197, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
ERROR 2024-07-01 21:36:15,060 basehttp 3500 26260 "GET /shop/orders/2 HTTP/1.1" 500 161614
ERROR 2024-07-01 21:36:15,910 log 3500 20568 Internal Server Error: /shop/orders/2
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 23, in get_orders
    return render(request, 'hw_2app/orders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\defaulttags.py", line 197, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
ERROR 2024-07-01 21:36:15,918 basehttp 3500 20568 "GET /shop/orders/2 HTTP/1.1" 500 161340
ERROR 2024-07-01 21:39:10,949 log 3500 20568 Internal Server Error: /shop/orders/2
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 23, in get_orders
    return render(request, 'hw_2app/orders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\defaulttags.py", line 197, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
ERROR 2024-07-01 21:39:10,967 basehttp 3500 20568 "GET /shop/orders/2 HTTP/1.1" 500 161751
INFO 2024-07-01 21:39:49,951 basehttp 3500 20568 "GET /shop/orders/2 HTTP/1.1" 200 554
INFO 2024-07-01 21:42:57,395 basehttp 3500 20568 "GET /shop/orders/1 HTTP/1.1" 200 659
INFO 2024-07-01 21:49:48,087 autoreload 3500 16004 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-01 21:49:48,506 autoreload 21660 26716 Watching for file changes with StatReloader
ERROR 2024-07-01 21:49:51,845 log 21660 16864 Internal Server Error: /shop/orders/1
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 18, in get_orders
    products = Product.objects.get()
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
hw_2app.models.Product.MultipleObjectsReturned: get() returned more than one Product -- it returned 6!
ERROR 2024-07-01 21:49:51,851 basehttp 21660 16864 "GET /shop/orders/1 HTTP/1.1" 500 76499
ERROR 2024-07-01 21:50:47,540 log 21660 16864 Internal Server Error: /shop/orders/1
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 18, in get_orders
    products = Product.objects.get()
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
hw_2app.models.Product.MultipleObjectsReturned: get() returned more than one Product -- it returned 6!
ERROR 2024-07-01 21:50:47,540 basehttp 21660 16864 "GET /shop/orders/1 HTTP/1.1" 500 76499
ERROR 2024-07-01 21:50:49,431 log 21660 16864 Internal Server Error: /shop/orders/1
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 18, in get_orders
    products = Product.objects.get()
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
hw_2app.models.Product.MultipleObjectsReturned: get() returned more than one Product -- it returned 6!
ERROR 2024-07-01 21:50:49,440 basehttp 21660 16864 "GET /shop/orders/1 HTTP/1.1" 500 76499
INFO 2024-07-01 21:51:08,198 autoreload 21660 26716 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-01 21:51:08,748 autoreload 9808 24068 Watching for file changes with StatReloader
INFO 2024-07-01 21:51:13,681 basehttp 9808 5076 "GET /shop/orders/1 HTTP/1.1" 200 1095
INFO 2024-07-01 22:11:49,292 autoreload 9808 24068 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-01 22:11:49,693 autoreload 10620 22596 Watching for file changes with StatReloader
INFO 2024-07-01 22:21:19,517 autoreload 10620 22596 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-01 22:21:20,047 autoreload 22604 26328 Watching for file changes with StatReloader
INFO 2024-07-01 22:25:59,914 autoreload 22604 26328 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-01 22:26:00,392 autoreload 22116 1992 Watching for file changes with StatReloader
INFO 2024-07-01 22:30:51,392 autoreload 22116 1992 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-01 22:30:51,936 autoreload 2368 26136 Watching for file changes with StatReloader
INFO 2024-07-01 22:31:00,779 basehttp 2368 27436 "GET /shop/orders/1 HTTP/1.1" 200 692
ERROR 2024-07-01 22:37:08,080 log 2368 2356 Internal Server Error: /shop/orders/1
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 28, in get_orders
    return render(request, 'hw_2app/orders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR 2024-07-01 22:37:08,080 basehttp 2368 2356 "GET /shop/orders/1 HTTP/1.1" 500 183464
INFO 2024-07-01 22:37:29,625 basehttp 2368 2356 "GET /shop/orders/1 HTTP/1.1" 200 634
INFO 2024-07-01 22:38:34,467 basehttp 2368 2356 "GET /shop/orders/1 HTTP/1.1" 200 634
INFO 2024-07-01 22:39:40,803 basehttp 2368 2356 "GET /shop/orders/1 HTTP/1.1" 200 673
INFO 2024-07-01 22:41:27,839 basehttp 2368 2356 "GET /shop/orders/1 HTTP/1.1" 200 708
INFO 2024-07-01 22:44:24,338 basehttp 2368 2356 "GET /shop/orders/1 HTTP/1.1" 200 820
INFO 2024-07-01 23:17:18,865 autoreload 15060 2636 Watching for file changes with StatReloader
INFO 2024-07-01 23:17:22,773 basehttp 15060 9128 "GET /shop/orders/1 HTTP/1.1" 200 1100
INFO 2024-07-01 23:22:59,056 autoreload 12824 21424 Watching for file changes with StatReloader
INFO 2024-07-01 23:23:02,235 basehttp 12824 21984 "GET /shop/orders/1 HTTP/1.1" 200 994
INFO 2024-07-02 20:29:17,762 autoreload 11484 3616 Watching for file changes with StatReloader
INFO 2024-07-02 20:29:21,541 basehttp 11484 19164 "GET /shop/orders/1 HTTP/1.1" 200 712
INFO 2024-07-02 20:31:01,777 autoreload 25624 16616 Watching for file changes with StatReloader
INFO 2024-07-02 20:31:05,493 basehttp 25624 23272 "GET /shop/orders/1 HTTP/1.1" 200 1557
INFO 2024-07-02 20:33:56,398 autoreload 26800 12148 Watching for file changes with StatReloader
INFO 2024-07-02 20:34:01,230 basehttp 26800 14400 "GET /shop/orders/3 HTTP/1.1" 200 1561
INFO 2024-07-02 21:01:18,092 autoreload 26800 12148 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-02 21:01:18,547 autoreload 4368 26512 Watching for file changes with StatReloader
INFO 2024-07-02 21:02:07,167 autoreload 4368 26512 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-02 21:02:07,554 autoreload 21196 11324 Watching for file changes with StatReloader
INFO 2024-07-02 21:27:57,938 autoreload 21196 11324 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-02 21:27:59,079 autoreload 15960 2836 Watching for file changes with StatReloader
INFO 2024-07-03 20:28:09,801 autoreload 15960 2836 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:28:10,242 autoreload 9152 14796 Watching for file changes with StatReloader
INFO 2024-07-03 20:28:22,452 autoreload 9152 14796 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:28:22,834 autoreload 21980 26948 Watching for file changes with StatReloader
INFO 2024-07-03 20:28:34,072 autoreload 21980 26948 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:28:34,448 autoreload 13728 14076 Watching for file changes with StatReloader
INFO 2024-07-03 20:29:04,907 autoreload 13728 14076 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:29:05,331 autoreload 19960 4092 Watching for file changes with StatReloader
INFO 2024-07-03 20:29:33,861 autoreload 19960 4092 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:29:34,206 autoreload 9316 17380 Watching for file changes with StatReloader
INFO 2024-07-03 20:33:16,367 autoreload 9316 17380 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:33:16,788 autoreload 1064 21312 Watching for file changes with StatReloader
INFO 2024-07-03 20:37:34,164 autoreload 1064 21312 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:37:34,571 autoreload 16036 7704 Watching for file changes with StatReloader
INFO 2024-07-03 20:46:59,029 autoreload 16036 7704 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:46:59,447 autoreload 21308 5448 Watching for file changes with StatReloader
WARNING 2024-07-03 20:47:01,629 log 21308 14400 Not Found: /
WARNING 2024-07-03 20:47:01,629 basehttp 21308 14400 "GET / HTTP/1.1" 404 2166
WARNING 2024-07-03 20:47:10,716 log 21308 14400 Not Found: /
WARNING 2024-07-03 20:47:10,717 basehttp 21308 14400 "GET / HTTP/1.1" 404 2166
WARNING 2024-07-03 20:47:17,942 log 21308 14400 Not Found: /shop/orders/
WARNING 2024-07-03 20:47:17,942 basehttp 21308 14400 "GET /shop/orders/ HTTP/1.1" 404 2694
ERROR 2024-07-03 20:47:26,025 log 21308 14400 Internal Server Error: /shop/orders/3/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 39, in sort_orders_by_period
    if period >= (now - order.order_date):
                  ~~~~^~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-07-03 20:47:26,025 basehttp 21308 14400 "GET /shop/orders/3/7 HTTP/1.1" 500 68344
INFO 2024-07-03 20:48:37,734 autoreload 21308 5448 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:48:38,128 autoreload 15792 22924 Watching for file changes with StatReloader
WARNING 2024-07-03 20:48:49,245 log 15792 13692 Not Found: /
WARNING 2024-07-03 20:48:49,245 basehttp 15792 13692 "GET / HTTP/1.1" 404 2166
INFO 2024-07-03 20:48:49,512 autoreload 15792 22924 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:48:49,986 autoreload 22568 1708 Watching for file changes with StatReloader
WARNING 2024-07-03 20:48:51,259 log 22568 21672 Not Found: /
WARNING 2024-07-03 20:48:51,259 basehttp 22568 21672 "GET / HTTP/1.1" 404 2166
WARNING 2024-07-03 20:48:55,833 log 22568 21672 Not Found: /shop/orders/
WARNING 2024-07-03 20:48:55,833 basehttp 22568 21672 "GET /shop/orders/ HTTP/1.1" 404 2694
ERROR 2024-07-03 20:49:04,565 log 22568 21672 Internal Server Error: /shop/orders/3/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 39, in sort_orders_by_period
    if period >= (now - order.order_date).days:
                  ~~~~^~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-07-03 20:49:04,572 basehttp 22568 21672 "GET /shop/orders/3/7 HTTP/1.1" 500 68353
ERROR 2024-07-03 20:49:20,831 log 22568 21672 Internal Server Error: /shop/orders/3/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 39, in sort_orders_by_period
    if period >= (now - order.order_date).days:
                  ~~~~^~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-07-03 20:49:20,831 basehttp 22568 21672 "GET /shop/orders/3/7 HTTP/1.1" 500 68491
INFO 2024-07-03 20:51:15,851 autoreload 22568 1708 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 20:51:16,240 autoreload 23384 10944 Watching for file changes with StatReloader
ERROR 2024-07-03 20:51:24,615 log 23384 4116 Internal Server Error: /shop/orders/3/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 38, in sort_orders_by_period
    order_period = now - order.order_date
                   ~~~~^~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-07-03 20:51:24,615 basehttp 23384 4116 "GET /shop/orders/3/7 HTTP/1.1" 500 68257
ERROR 2024-07-03 20:51:28,431 log 23384 4116 Internal Server Error: /shop/orders/3/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 38, in sort_orders_by_period
    order_period = now - order.order_date
                   ~~~~^~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-07-03 20:51:28,433 basehttp 23384 4116 "GET /shop/orders/3/7 HTTP/1.1" 500 68257
INFO 2024-07-03 21:03:01,655 autoreload 23384 10944 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 21:03:02,038 autoreload 8748 17416 Watching for file changes with StatReloader
WARNING 2024-07-03 21:03:47,249 log 8748 8884 Not Found: /
WARNING 2024-07-03 21:03:47,249 basehttp 8748 8884 "GET / HTTP/1.1" 404 2166
WARNING 2024-07-03 21:03:54,673 log 8748 8884 Not Found: /
WARNING 2024-07-03 21:03:54,674 basehttp 8748 8884 "GET / HTTP/1.1" 404 2166
ERROR 2024-07-03 21:04:07,297 log 8748 8884 Internal Server Error: /shop/orders/1/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 38, in sort_orders_by_period
    order_period = now - order.order_date
                   ~~~~^~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-07-03 21:04:07,297 basehttp 8748 8884 "GET /shop/orders/1/7 HTTP/1.1" 500 68115
INFO 2024-07-03 21:08:03,532 autoreload 8748 17416 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 21:08:03,930 autoreload 13288 3616 Watching for file changes with StatReloader
INFO 2024-07-03 21:09:36,440 autoreload 13288 3616 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 21:09:36,914 autoreload 26120 24700 Watching for file changes with StatReloader
WARNING 2024-07-03 21:09:39,742 log 26120 20672 Not Found: /
WARNING 2024-07-03 21:09:39,748 basehttp 26120 20672 "GET / HTTP/1.1" 404 2166
ERROR 2024-07-03 21:09:51,132 log 26120 20672 Internal Server Error: /shop/orders/1/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 40, in sort_orders_by_period
    if order.order_date >= find_period:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR 2024-07-03 21:09:51,132 basehttp 26120 20672 "GET /shop/orders/1/7 HTTP/1.1" 500 68520
INFO 2024-07-03 21:11:21,162 autoreload 26120 24700 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 21:11:21,636 autoreload 24420 25388 Watching for file changes with StatReloader
ERROR 2024-07-03 21:11:26,493 log 24420 16424 Internal Server Error: /shop/orders/1/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 43, in sort_orders_by_period
    if order.order_date >= find_period:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR 2024-07-03 21:11:26,493 basehttp 24420 16424 "GET /shop/orders/1/7 HTTP/1.1" 500 68610
ERROR 2024-07-03 21:11:30,280 log 24420 16424 Internal Server Error: /shop/orders/1/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 43, in sort_orders_by_period
    if order.order_date >= find_period:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR 2024-07-03 21:11:30,280 basehttp 24420 16424 "GET /shop/orders/1/7 HTTP/1.1" 500 68610
INFO 2024-07-03 21:12:28,922 autoreload 24420 25388 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 21:12:29,326 autoreload 19048 20452 Watching for file changes with StatReloader
INFO 2024-07-03 21:12:34,554 basehttp 19048 2136 "GET /shop/orders/1/7 HTTP/1.1" 200 1500
INFO 2024-07-03 21:14:13,358 autoreload 19048 20452 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 21:14:13,698 autoreload 21932 18736 Watching for file changes with StatReloader
INFO 2024-07-03 21:14:17,774 basehttp 21932 3324 "GET /shop/orders/1/7 HTTP/1.1" 200 1516
INFO 2024-07-03 21:20:08,003 autoreload 992 21588 Watching for file changes with StatReloader
WARNING 2024-07-03 21:20:10,155 log 992 26428 Not Found: /
WARNING 2024-07-03 21:20:10,155 basehttp 992 26428 "GET / HTTP/1.1" 404 2166
INFO 2024-07-03 21:20:25,837 basehttp 992 26428 "GET /shop/orders/1/7 HTTP/1.1" 200 1439
INFO 2024-07-03 21:20:47,025 autoreload 992 21588 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 21:20:47,371 autoreload 20876 22988 Watching for file changes with StatReloader
ERROR 2024-07-03 21:20:51,570 log 20876 22220 Internal Server Error: /shop/orders/1/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 43, in sort_orders_by_period
    if order.order_date >= find_period:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'datetime.datetime'
ERROR 2024-07-03 21:20:51,574 basehttp 20876 22220 "GET /shop/orders/1/7 HTTP/1.1" 500 68836
ERROR 2024-07-03 21:22:19,562 log 20876 22220 Internal Server Error: /shop/orders/1/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 43, in sort_orders_by_period
    if order.order_date >= find_period:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'datetime.datetime'
ERROR 2024-07-03 21:22:19,562 basehttp 20876 22220 "GET /shop/orders/1/7 HTTP/1.1" 500 68836
ERROR 2024-07-03 21:22:21,437 log 20876 22220 Internal Server Error: /shop/orders/1/7
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 43, in sort_orders_by_period
    if order.order_date >= find_period:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'datetime.datetime'
ERROR 2024-07-03 21:22:21,439 basehttp 20876 22220 "GET /shop/orders/1/7 HTTP/1.1" 500 68836
INFO 2024-07-03 21:23:23,993 autoreload 20876 22988 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 21:23:24,418 autoreload 11064 25368 Watching for file changes with StatReloader
INFO 2024-07-03 21:23:27,913 basehttp 11064 14748 "GET /shop/orders/1/7 HTTP/1.1" 200 1439
INFO 2024-07-03 21:26:09,048 autoreload 4296 10164 Watching for file changes with StatReloader
INFO 2024-07-03 21:26:12,364 basehttp 4296 21472 "GET /shop/orders/1/7 HTTP/1.1" 200 1691
INFO 2024-07-03 21:30:23,972 basehttp 4296 21472 "GET /shop/orders/1/7 HTTP/1.1" 200 1691
INFO 2024-07-03 21:30:27,457 basehttp 4296 21472 "GET /shop/orders/1/7 HTTP/1.1" 200 1691
INFO 2024-07-03 21:31:47,334 basehttp 4296 21472 "GET /shop/orders/1/7 HTTP/1.1" 200 1691
INFO 2024-07-03 21:31:52,047 basehttp 4296 21472 "GET /shop/orders/1/7 HTTP/1.1" 200 1691
INFO 2024-07-03 21:40:15,175 autoreload 11456 12616 Watching for file changes with StatReloader
INFO 2024-07-03 21:40:22,862 basehttp 11456 3912 "GET /shop/orders/1/7 HTTP/1.1" 200 1691
WARNING 2024-07-03 21:40:22,876 log 11456 3912 Not Found: /favicon.ico
WARNING 2024-07-03 21:40:22,877 basehttp 11456 3912 "GET /favicon.ico HTTP/1.1" 404 2217
INFO 2024-07-03 21:40:58,053 basehttp 11456 11904 "GET /shop/orders/1/7 HTTP/1.1" 200 1691
INFO 2024-07-03 21:41:14,742 basehttp 11456 11904 "GET /shop/orders/3/45 HTTP/1.1" 200 1443
INFO 2024-07-03 21:42:27,171 basehttp 11456 11904 "GET /shop/orders/3/45 HTTP/1.1" 200 1443
INFO 2024-07-03 21:42:39,330 basehttp 11456 11904 "GET /shop/orders/1/45 HTTP/1.1" 200 1692
INFO 2024-07-03 21:43:59,838 autoreload 4404 14700 Watching for file changes with StatReloader
INFO 2024-07-03 21:44:03,883 basehttp 4404 12904 "GET /shop/orders/1/45 HTTP/1.1" 200 1684
INFO 2024-07-03 22:02:05,831 autoreload 4404 14700 D:\GB\Django\Djangofirstproject\homework\hw_2app\models.py changed, reloading.
INFO 2024-07-03 22:02:06,151 autoreload 18088 2336 Watching for file changes with StatReloader
INFO 2024-07-03 22:02:24,554 autoreload 18088 2336 D:\GB\Django\Djangofirstproject\homework\hw_2app\models.py changed, reloading.
INFO 2024-07-03 22:02:24,853 autoreload 10324 2304 Watching for file changes with StatReloader
INFO 2024-07-03 22:03:12,099 autoreload 5496 12688 Watching for file changes with StatReloader
INFO 2024-07-03 22:03:20,081 basehttp 5496 7392 "GET /shop/orders/1/45 HTTP/1.1" 200 1684
INFO 2024-07-03 22:06:31,287 autoreload 8172 15336 Watching for file changes with StatReloader
INFO 2024-07-03 22:06:37,079 basehttp 8172 2004 "GET /shop/orders/1/45 HTTP/1.1" 200 1259
INFO 2024-07-03 22:07:00,123 autoreload 8172 15336 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 22:07:00,471 autoreload 4404 5040 Watching for file changes with StatReloader
ERROR 2024-07-03 22:07:15,872 log 4404 7908 Internal Server Error: /shop/orders/1/45
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 43, in sort_orders_by_period
    if order.order_date >= find_period:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
ERROR 2024-07-03 22:07:15,873 basehttp 4404 7908 "GET /shop/orders/1/45 HTTP/1.1" 500 68619
INFO 2024-07-03 22:18:17,625 autoreload 4404 5040 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 22:18:17,934 autoreload 16892 8672 Watching for file changes with StatReloader
INFO 2024-07-03 22:18:25,123 autoreload 16892 8672 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 22:18:25,406 autoreload 12648 2492 Watching for file changes with StatReloader
INFO 2024-07-03 22:19:51,397 autoreload 3648 1360 Watching for file changes with StatReloader
ERROR 2024-07-03 22:19:57,801 log 3648 5468 Internal Server Error: /shop/orders/1/45
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 42, in sort_orders_by_period
    print(utc.localize(order.order_date))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\pytz\__init__.py", line 245, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
ERROR 2024-07-03 22:19:57,801 basehttp 3648 5468 "GET /shop/orders/1/45 HTTP/1.1" 500 72481
INFO 2024-07-03 22:20:57,746 autoreload 3648 1360 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 22:20:58,045 autoreload 2632 3352 Watching for file changes with StatReloader
ERROR 2024-07-03 22:21:02,583 log 2632 6856 Internal Server Error: /shop/orders/1/45
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 42, in sort_orders_by_period
    order.order_date = utc.localize(order.order_date)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\pytz\__init__.py", line 245, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
ERROR 2024-07-03 22:21:02,583 basehttp 2632 6856 "GET /shop/orders/1/45 HTTP/1.1" 500 72529
INFO 2024-07-03 22:21:54,195 autoreload 2632 3352 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 22:21:54,490 autoreload 8584 5192 Watching for file changes with StatReloader
ERROR 2024-07-03 22:22:03,900 log 8584 3032 Internal Server Error: /shop/orders/1/45
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 42, in sort_orders_by_period
    order.order_date = utc.localize(order.order_date)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\pytz\__init__.py", line 245, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
ERROR 2024-07-03 22:22:03,900 basehttp 8584 3032 "GET /shop/orders/1/45 HTTP/1.1" 500 72583
ERROR 2024-07-03 22:22:06,517 log 8584 3032 Internal Server Error: /shop/orders/1/45
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 42, in sort_orders_by_period
    order.order_date = utc.localize(order.order_date)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\pytz\__init__.py", line 245, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
ERROR 2024-07-03 22:22:06,517 basehttp 8584 3032 "GET /shop/orders/1/45 HTTP/1.1" 500 72583
INFO 2024-07-03 22:22:45,565 autoreload 8584 5192 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-03 22:22:45,893 autoreload 2760 10924 Watching for file changes with StatReloader
INFO 2024-07-03 22:22:50,578 basehttp 2760 13964 "GET /shop/orders/1/45 HTTP/1.1" 200 1259
INFO 2024-07-10 22:09:14,629 autoreload 22544 6172 Watching for file changes with StatReloader
INFO 2024-07-10 22:11:21,286 autoreload 22544 6172 D:\GB\Django\Djangofirstproject\homework\hw_2app\forms.py changed, reloading.
INFO 2024-07-10 22:11:21,792 autoreload 19240 4268 Watching for file changes with StatReloader
INFO 2024-07-10 22:11:46,599 autoreload 19240 4268 D:\GB\Django\Djangofirstproject\homework\hw_2app\forms.py changed, reloading.
INFO 2024-07-10 22:11:47,020 autoreload 15952 22832 Watching for file changes with StatReloader
WARNING 2024-07-10 22:11:49,781 log 15952 18940 Not Found: /
WARNING 2024-07-10 22:11:49,781 basehttp 15952 18940 "GET / HTTP/1.1" 404 2166
INFO 2024-07-10 22:12:10,937 basehttp 15952 18940 "GET /shop/ HTTP/1.1" 200 502
INFO 2024-07-10 22:12:43,650 basehttp 15952 18940 "GET /shop/update_product HTTP/1.1" 301 0
ERROR 2024-07-10 22:12:43,718 log 15952 20148 Internal Server Error: /shop/update_product/
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 71, in update_product
    return render(request, 'hw_2app/product_form.html', {'form': form, 'message': message})
                                                                                  ^^^^^^^
UnboundLocalError: cannot access local variable 'message' where it is not associated with a value
ERROR 2024-07-10 22:12:43,724 basehttp 15952 20148 "GET /shop/update_product/ HTTP/1.1" 500 67212
INFO 2024-07-10 22:13:19,309 autoreload 15952 22832 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-10 22:13:19,863 autoreload 20892 14700 Watching for file changes with StatReloader
INFO 2024-07-10 22:13:24,940 basehttp 20892 23044 "GET /shop/update_product/ HTTP/1.1" 200 1738
INFO 2024-07-10 22:14:39,030 basehttp 20892 23044 "POST /shop/update_product/ HTTP/1.1" 200 1785
INFO 2024-07-10 22:16:38,134 autoreload 20892 14700 D:\GB\Django\Djangofirstproject\homework\hw_2app\forms.py changed, reloading.
INFO 2024-07-10 22:16:38,539 autoreload 1644 14304 Watching for file changes with StatReloader
ERROR 2024-07-10 22:16:50,331 log 1644 16344 Internal Server Error: /shop/update_product/
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 68, in update_product
    product.save()
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1040, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1105, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2024-07-10 22:16:50,338 basehttp 1644 16344 "POST /shop/update_product/ HTTP/1.1" 500 151513
ERROR 2024-07-10 22:17:04,116 log 1644 16344 Internal Server Error: /shop/update_product/
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 68, in update_product
    product.save()
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1040, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1105, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2024-07-10 22:17:04,121 basehttp 1644 16344 "POST /shop/update_product/ HTTP/1.1" 500 151513
INFO 2024-07-10 22:17:15,923 basehttp 1644 16344 "POST /shop/update_product/ HTTP/1.1" 200 1785
INFO 2024-07-10 22:17:18,683 basehttp 1644 16344 "POST /shop/update_product/ HTTP/1.1" 200 1785
INFO 2024-07-10 22:19:53,820 autoreload 1644 14304 D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py changed, reloading.
INFO 2024-07-10 22:19:54,242 autoreload 9784 15132 Watching for file changes with StatReloader
ERROR 2024-07-10 22:20:10,872 log 9784 22956 Internal Server Error: /shop/update_product/
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 69, in update_product
    product.save()
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1040, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1105, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2024-07-10 22:20:10,872 basehttp 9784 22956 "POST /shop/update_product/ HTTP/1.1" 500 151565
ERROR 2024-07-10 22:20:10,921 log 9784 11952 Internal Server Error: /shop/update_product/
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 69, in update_product
    product.save()
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1040, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1105, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
INFO 2024-07-10 22:20:10,921 basehttp 9784 11952 - Broken pipe from ('127.0.0.1', 59748)
INFO 2024-07-10 22:20:27,427 basehttp 9784 22956 "POST /shop/update_product/ HTTP/1.1" 200 1785
INFO 2024-07-10 22:20:30,768 basehttp 9784 22956 "POST /shop/update_product/ HTTP/1.1" 200 1785
INFO 2024-07-10 22:24:14,167 basehttp 9784 22956 "POST /shop/update_product/ HTTP/1.1" 200 1852
INFO 2024-07-10 22:31:58,996 basehttp 9784 13684 "POST /shop/update_product/ HTTP/1.1" 200 1895
INFO 2024-07-10 22:32:03,692 basehttp 9784 13684 "POST /shop/update_product/ HTTP/1.1" 200 1895
INFO 2024-07-10 22:32:21,599 basehttp 9784 13684 "POST /shop/update_product/ HTTP/1.1" 200 1895
INFO 2024-07-10 22:32:31,619 basehttp 9784 13684 "GET /shop/update_product/ HTTP/1.1" 200 1828
INFO 2024-07-10 22:33:55,205 basehttp 9784 13684 "POST /shop/update_product/ HTTP/1.1" 200 1904
INFO 2024-07-10 22:34:47,794 autoreload 9784 15132 D:\GB\Django\Djangofirstproject\homework\hw_2app\forms.py changed, reloading.
INFO 2024-07-10 22:34:48,266 autoreload 21552 9828 Watching for file changes with StatReloader
ERROR 2024-07-10 22:34:56,805 log 21552 15092 Internal Server Error: /shop/update_product/
Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\homework\hw_2app\views.py", line 69, in update_product
    product.save()
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1040, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\base.py", line 1105, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Djangofirstproject\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2024-07-10 22:34:56,813 basehttp 21552 15092 "POST /shop/update_product/ HTTP/1.1" 500 151574
INFO 2024-07-10 22:35:10,051 basehttp 21552 15092 "POST /shop/update_product/ HTTP/1.1" 200 1916
INFO 2024-07-10 22:36:21,267 autoreload 21552 9828 D:\GB\Django\Djangofirstproject\homework\hw_2app\forms.py changed, reloading.
INFO 2024-07-10 22:36:21,813 autoreload 22544 14016 Watching for file changes with StatReloader
INFO 2024-07-10 22:36:25,841 basehttp 22544 16172 "POST /shop/update_product/ HTTP/1.1" 200 1950
INFO 2024-07-10 22:37:47,219 autoreload 22544 14016 D:\GB\Django\Djangofirstproject\homework\hw_2app\forms.py changed, reloading.
INFO 2024-07-10 22:37:47,696 autoreload 19836 18232 Watching for file changes with StatReloader
INFO 2024-07-10 22:37:52,356 basehttp 19836 13720 "POST /shop/update_product/ HTTP/1.1" 200 1887
